# Generated by Django 3.2.6 on 2022-05-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='share',
            field=models.BooleanField(default=False, null=True, verbose_name='Share folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='unique_folder_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
