# Generated by Django 3.2.6 on 2022-06-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220530_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='full_path',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
