# Generated by Django 3.2.6 on 2022-06-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company_full_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='full_path',
        ),
        migrations.AddField(
            model_name='folder',
            name='full_path',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
